replicaCount: 1

namespace: ired
appname: ired
appname1: ired-amplasia
appname2: ired-iplasia
appname3: ired-lulasia
appname4: ired-mglafrica
appname5: ired-mglamerica
appname6: ired-mglasiafive
appname7: ired-mglasiafour
appname8: ired-mglasiathree
appname9: ired-mglasiatwo
appname10: ired-mglasiaone
appname11: ired-mglasiasix
appname12: ired-sulasia
appname13: ired-europe
appname14: ired-dev


image:
  repository: asia.gcr.io/iplon-india/ired302
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  port: 1880
  portname: ired-http

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configmap_nodered:
  name: ired-amplasia
  mountpath: "/usr/lib/node_modules/node-red/settings.js"
  subpath: "settings.js"



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext:
   runAsUser: 0

ingress:
  class: public-ingress
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: ired-ingress
    kubernetes.io/ingress.class: public-ingress
    cert-manager.io/cluster-issuer: "letsencrypt-public-ingress"
    kubernetes.io/force-ssl-redirect: 'true'
    # kubernetes.io/ingress.allow-http: "false"
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.org/client-max-body-size: "999m"
  hosts:
    host: ired.iplon.co.in
    path: "/"
  amplasia:
    host: ired.iplon.co.in
    path: "/amplasia"
  iplasia:
    host: ired.iplon.co.in
    path: "/iplasia"
  lulasia:
    host: ired.iplon.co.in
    path: "/lulasia"
  africa:
    host: ired.iplon.co.in
    path: "/africa"
  america:
    host: ired.iplon.co.in
    path: "/america"
  asiafive:
    host: ired.iplon.co.in
    path: "/asiafive"
  asiafour:
    host: ired.iplon.co.in
    path: "/asiafour"
  asiathree:
    host: ired.iplon.co.in
    path: "/asiathree"
  asiatwo:
    host: ired.iplon.co.in
    path: "/asiatwo"
  asiaone:
    host: ired.iplon.co.in
    path: "/asiaone"

  asiasix:
    host: ired.iplon.co.in
    path: "/asiasix"

  sulasia:
    host: ired.iplon.co.in
    path: "/sulasia"

  europe:
    host: ired.iplon.co.in
    path: "/europe"

  dev:
    host: ired.iplon.co.in
    path: "/dev"


  tls:
    secretName: ired-secret-prod
    host: ired.iplon.co.in

service:
  type: ClusterIP
  port: 80


resources:
  limits:
    cpu: 85m
    memory: 550Mi
  requests:
    cpu: 50m
    memory: 300Mi

nodered_mount:
   name: flowstoragemount
   path: /data
   subpath: ""

nodeflow_storage:
  pvname: ired-amplasia-pv
  pvcname: ired-amplasia-pvc
  size: 10Gi
  mountpath: /mnt/nfsdisk/ired/
  nfsserver: nfs-external-apps.asia-south1-a.c.iplon-india.internal
  accessModes: ReadWriteMany
  storageClassName: premium-rwx

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}